<?php

if (function_exists('acf_add_local_field_group')) :

    acf_add_local_field_group(array(
        'key' => 'group_5c62f0486a79d',
        'title' => 'Banner',
        'fields' => array(
            array(
                'key' => 'field_5c62f68226c7a',
                'label' => 'Ativar modulo',
                'name' => 'ativarBanner',
                'type' => 'true_false',
                'value' => NULL,
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array (
                'key' => 'field_5ca75f2ebddasd430b',
                'label' => 'Imagens Background Mobile',
                'name' => 'bgMobileBanner',
                'type' => 'repeater',
                'value' => NULL,
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array (
                    array (
                        array (
                            'field' => 'field_5c62f68226c7a',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'row',
                'button_label' => '',
                'sub_fields' => array (
                    array (
                        'key' => 'field_5ca75f5ddasfgw8b430d',
                        'label' => 'Background',
                        'name' => 'background',
                        'type' => 'image',
                        'value' => NULL,
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'url',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                    ),
                ),
            ),
            array (
                'key' => 'field_5ca75f2egasddbddasd430b',
                'label' => 'Imagens Background HD',
                'name' => 'bgBannerHD',
                'type' => 'repeater',
                'value' => NULL,
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array (
                    array (
                        array (
                            'field' => 'field_5c62f68226c7a',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'row',
                'button_label' => '',
                'sub_fields' => array (
                    array (
                        'key' => 'field_5ca75f5ddggsasfgw8b430d',
                        'label' => 'Background',
                        'name' => 'background',
                        'type' => 'image',
                        'value' => NULL,
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'url',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_5c630e9eddasddasde2s886',
                'label' => 'Imagem Logo',
                'name' => 'logoEventoBanner',
                'type' => 'image',
                'value' => NULL,
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5c62f68226c7a',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'url',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            // array(
            //     'key' => 'field_5c62f7c12ddasdddaasds33626c7e',
            //     'label' => 'Primeira Frase Título',
            //     'name' => 'primeiraFraseTitulo',
            //     'type' => 'text',
            //     'value' => NULL,
            //     'instructions' => '',
            //     'required' => 0,
            //     'conditional_logic' => array(
            //         array(
            //             array(
            //                 'field' => 'field_5c62f68226c7a',
            //                 'operator' => '==',
            //                 'value' => '1',
            //             ),
            //         ),
            //     ),
            //     'wrapper' => array(
            //         'width' => '',
            //         'class' => '',
            //         'id' => '',
            //     ),
            //     'default_value' => '',
            //     'placeholder' => '',
            //     'prepend' => '',
            //     'append' => '',
            //     'maxlength' => '',
            // ),
            // array(
            //     'key' => 'field_5c62f7c12ddasdddas33626c7e',
            //     'label' => 'Segunda Frase Título',
            //     'name' => 'segundaFraseTitulo',
            //     'type' => 'text',
            //     'value' => NULL,
            //     'instructions' => '',
            //     'required' => 0,
            //     'conditional_logic' => array(
            //         array(
            //             array(
            //                 'field' => 'field_5c62f68226c7a',
            //                 'operator' => '==',
            //                 'value' => '1',
            //             ),
            //         ),
            //     ),
            //     'wrapper' => array(
            //         'width' => '',
            //         'class' => '',
            //         'id' => '',
            //     ),
            //     'default_value' => '',
            //     'placeholder' => '',
            //     'prepend' => '',
            //     'append' => '',
            //     'maxlength' => '',
            // ),
            array(
                'key' => 'field_5c62f7c12ddas33626c7e',
                'label' => 'Texto Banner',
                'name' => 'textoBanner',
                'type' => 'text',
                'value' => NULL,
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5c62f68226c7a',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5c630dasdase9ddassdwdee28ddasd86',
                'label' => 'Icon Whatsapp',
                'name' => 'iconWhatsapp',
                'type' => 'image',
                'value' => NULL,
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5c62f68226c7a',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'url',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'field_5c62f87826c80',
                'label' => 'Texto Botão Contato',
                'name' => 'textoInscrevasseBanner',
                'type' => 'text',
                'value' => NULL,
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5c62f68226c7a',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5c630025b26df',
                'label' => 'Link WhastApp',
                'name' => 'linkInscrevasseBanner',
                'type' => 'text',
                'value' => NULL,
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5c62f68226c7a',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5c6ddas30dasdase9ee2886',
                'label' => 'Logos Patrocinio',
                'name' => 'logosPatrocinio',
                'type' => 'image',
                'value' => NULL,
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5c62f68226c7a',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'url',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'default',
                ),
            ),
        ),
        'menu_order' => 2,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => array(
            0 => 'the_content',
        ),
        'active' => 1,
        'description' => '',
    ));

endif;
