<?php
    $site_origem = json_decode(file_get_contents('https://news.ativo.com/api/newsorigem'),true);

    foreach ($site_origem as $origems){
        $origem_id = $origems["id"];
        $nome_origem = $origems["name"].' - '.$origems["id"];
        $optionOrigem[$origem_id] = $nome_origem;
    }
    if( function_exists('acf_add_local_field_group') ){
        acf_add_local_field_group(array (
            'key' => 'group_5babd57f2df04e5',
            'title' => 'Newsletter',
            'fields' => array (
                array (
                    'key' => 'field_5babd6a1f79f3',
                    'label' => 'Origem',
                    'name' => 'origemNewsletter',
                    'type' => 'select',
                    'value' => NULL,
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => $optionOrigem,
                    'default_value' => array (
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'ajax' => 0,
                    'return_format' => 'value',
                    'placeholder' => '',
                ),
                array (
                    'key' => 'field_5babd731f79f5',
                    'label' => 'Título',
                    'name' => 'tituloNewsletter',
                    'type' => 'text',
                    'value' => NULL,
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array (
                    'key' => 'field_5babd7defdasd2131f79f5',
                    'label' => 'Imagem News',
                    'name' => 'imgNews',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'url',
                    'preview_size' => 'thumbnail',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ),        
                // array (
                //     'key' => 'field_5babd7def31f79f5',
                //     'label' => 'Texto',
                //     'name' => 'textarea',
                //     'type' => 'text',
                //     'value' => NULL,
                //     'instructions' => '',
                //     'required' => 0,
                //     'conditional_logic' => 0,
                //     'wrapper' => array (
                //         'width' => '',
                //         'class' => '',
                //         'id' => '',
                //     ),
                //     'default_value' => '',
                //     'placeholder' => '',
                //     'prepend' => '',
                //     'append' => '',
                //     'maxlength' => '',
                // ),            
                array(
                    'key' => 'field_5ce441c453fadasdb73b50',
                    'label' => 'Imagem Botão',
                    'name' => 'Imgbotao',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'url',
                    'preview_size' => 'thumbnail',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ),
                array (
                    'key' => 'field_5babd80cf79f9',
                    'label' => 'Texto Placeholder E-mail',
                    'name' => 'placeholderEmail',
                    'type' => 'text',
                    'value' => NULL,
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array (
                    'key' => 'field_5babd83ff79fa',
                    'label' => 'Mensagem de sucesso',
                    'name' => 'mensagemSucesso',
                    'type' => 'text',
                    'value' => NULL,
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array (
                    'key' => 'field_5babd858f79fb',
                    'label' => 'Mensagem de erro',
                    'name' => 'mensagemErro',
                    'type' => 'text',
                    'value' => NULL,
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
            ),
            'location' => array (
                array (
                    array (
                        'param' => 'options_page',
                        'operator' => '==',
                        'value' => 'acf-options-newsletter',
                    ),
                ),
            ),
            'menu_order' => 20,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => array (
                0 => 'the_content',
            ),
            'active' => 1,
            'description' => '',
        ));
    }
?>