<?php
if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
        'key' => 'group_5de9bef8e1ff2',
        'title' => 'Tapume Historico',
        'fields' => array(
            array(
                'key' => 'field_5de9c03db3ff0',
                'label' => 'Background Mobile',
                'name' => 'background_mobile',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'url',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'field_5de9c21dbb645',
                'label' => 'Background',
                'name' => 'background_desk',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'url',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'field_5de9c066bsdf63ff1',
                'label' => 'Imagem logo evento',
                'name' => 'imgs_logo_eventos',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'url',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'field_60f7221b6c838',
                'label' => 'Cidades',
                'name' => 'cidades_btn',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'table',
                'button_label' => '',
                'sub_fields' => array(
                    // array(
                    //     'key' => 'field_60f7223e6c839',
                    //     'label' => 'Ícone localização',
                    //     'name' => 'icone_localizacao',
                    //     'type' => 'image',
                    //     'instructions' => '',
                    //     'required' => 0,
                    //     'conditional_logic' => 0,
                    //     'wrapper' => array(
                    //         'width' => '',
                    //         'class' => '',
                    //         'id' => '',
                    //     ),
                    //     'return_format' => 'url',
                    //     'preview_size' => 'thumbnail',
                    //     'library' => 'all',
                    //     'min_width' => '',
                    //     'min_height' => '',
                    //     'min_size' => '',
                    //     'max_width' => '',
                    //     'max_height' => '',
                    //     'max_size' => '',
                    //     'mime_types' => '',
                    // ),
                    array(
                        'key' => 'field_60f722786c83a',
                        'label' => 'Nome cidade',
                        'name' => 'nome_cidade',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_60f7228c6c83b',
                        'label' => 'Data',
                        'name' => 'data',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    // array(
                    //     'key' => 'field_60f722aa6c83d',
                    //     'label' => 'Ícone setas',
                    //     'name' => 'icone_setas',
                    //     'type' => 'image',
                    //     'instructions' => '',
                    //     'required' => 0,
                    //     'conditional_logic' => 0,
                    //     'wrapper' => array(
                    //         'width' => '',
                    //         'class' => '',
                    //         'id' => '',
                    //     ),
                    //     'return_format' => 'url',
                    //     'preview_size' => 'thumbnail',
                    //     'library' => 'all',
                    //     'min_width' => '',
                    //     'min_height' => '',
                    //     'min_size' => '',
                    //     'max_width' => '',
                    //     'max_height' => '',
                    //     'max_size' => '',
                    //     'mime_types' => '',
                    // ),
                    array(
                        'key' => 'field_60f722aa632sc83d',
                        'label' => 'Link cidade',
                        'name' => 'url_btn',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_5de9c066b3ff1',
                'label' => 'Img Logos',
                'name' => 'imgs_logos',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'url',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-tapume.php',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
    
    endif;
?>